### PR TITLE
[TR3FIR-240]: Implement polling with waker for TSC

### PR DESCRIPTION
**Pull request by BednarzAleksander**

### CODE REVIEW

**Review by mattcaron-token — CHANGES_REQUESTED** [review]
I'm sorry if I wasn't clear in my ticket, but this is a completely wrong approach:

1. It rewrites a large portion of the upstream driver, which is going to lead to a maintenance nightmare.
2. It also is going to invalidate any examples they write.
3. If this was purely additive, that would be fine - that is, it can be used in either polled or interrupt driven modes, but it replaces the polled mode with a solely interrupt-driven mode.
4. My intention with the ticket was that the waker be implemented one level up, e.g. in `board_support_package/src/button/tsc.rs` (or similar).

**Comment by BednarzAleksander** [comment]
> I'm sorry if I wasn't clear in my ticket, but this is a completely wrong approach:
> 
> 1. It rewrites a large portion of the upstream driver, which is going to lead to a maintenance nightmare.
> 2. It also is going to invalidate any examples they write.
> 3. If this was purely additive, that would be fine - that is, it can be used in either polled or interrupt driven modes, but it replaces the polled mode with a solely interrupt-driven mode.
> 4. My intention with the ticket was that the waker be implemented one level up, e.g. in `board_support_package/src/button/tsc.rs` (or similar).

I have analyzed the changes in Embassy, and support for async wait for TSC has been added in the main branch of Embassy. In my opinion, it doesn't make sense to implement our own changes since support for this functionality will be included with the upcoming merge.

**Comment by BednarzAleksander** [comment]
I added a comment for this in the Jira task: https://tokenring.atlassian.net/browse/TR3FIR-240

**Comment by mattcaron-token** [comment]
> I have analyzed the changes in Embassy, and support for async wait for TSC has been added in the main branch of Embassy. In my opinion, it doesn't make sense to implement our own changes since support for this functionality will be included with the upcoming merge.

I completely agree - and I think it sounds like a good thing for me to do after I'm finished with the flash sync.

**Pull request closed without merging**
